/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace GMPrizePool {
  export type WinnerStruct = {
    winnerAddress: string;
    prizeAmount: BigNumberish;
  };

  export type WinnerStructOutput = [string, BigNumber] & {
    winnerAddress: string;
    prizeAmount: BigNumber;
  };
}

export interface GMPrizePoolInterface extends utils.Interface {
  functions: {
    "depositPrize((address,uint256)[],uint256)": FunctionFragment;
    "expiredTime()": FunctionFragment;
    "getBackprize()": FunctionFragment;
    "getMyPrize()": FunctionFragment;
    "owner()": FunctionFragment;
    "redeemPrize()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositPrize"
      | "expiredTime"
      | "getBackprize"
      | "getMyPrize"
      | "owner"
      | "redeemPrize"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositPrize",
    values: [GMPrizePool.WinnerStruct[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expiredTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBackprize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyPrize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemPrize",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "depositPrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expiredTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBackprize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyPrize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemPrize",
    data: BytesLike
  ): Result;

  events: {
    "RedeemSuccess(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RedeemSuccess"): EventFragment;
}

export interface RedeemSuccessEventObject {
  sender: string;
  value: BigNumber;
}
export type RedeemSuccessEvent = TypedEvent<
  [string, BigNumber],
  RedeemSuccessEventObject
>;

export type RedeemSuccessEventFilter = TypedEventFilter<RedeemSuccessEvent>;

export interface GMPrizePool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GMPrizePoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositPrize(
      _winnersList: GMPrizePool.WinnerStruct[],
      _expiredTime: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    expiredTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBackprize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getMyPrize(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    redeemPrize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  depositPrize(
    _winnersList: GMPrizePool.WinnerStruct[],
    _expiredTime: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  expiredTime(overrides?: CallOverrides): Promise<BigNumber>;

  getBackprize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getMyPrize(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  redeemPrize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositPrize(
      _winnersList: GMPrizePool.WinnerStruct[],
      _expiredTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    expiredTime(overrides?: CallOverrides): Promise<BigNumber>;

    getBackprize(overrides?: CallOverrides): Promise<boolean>;

    getMyPrize(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    redeemPrize(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "RedeemSuccess(address,uint256)"(
      sender?: string | null,
      value?: null
    ): RedeemSuccessEventFilter;
    RedeemSuccess(
      sender?: string | null,
      value?: null
    ): RedeemSuccessEventFilter;
  };

  estimateGas: {
    depositPrize(
      _winnersList: GMPrizePool.WinnerStruct[],
      _expiredTime: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    expiredTime(overrides?: CallOverrides): Promise<BigNumber>;

    getBackprize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    getMyPrize(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    redeemPrize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;
  };

  populateTransaction: {
    depositPrize(
      _winnersList: GMPrizePool.WinnerStruct[],
      _expiredTime: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    expiredTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBackprize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getMyPrize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeemPrize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
